name: Deploy Otorno Report to GitHub Pages

on:
  push:
    branches: [ main ]  # or your working branch

jobs:
  deploy-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Deploy report-db to gh-pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report-db

      - name: Upload Otorno HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: otorno-report
          path: report-db/
